package com.jarvis.deploy.event;

public enum DeploymentEventType {
    DEPLOYMENT_STARTED,
    DEPLOYMENT_COMPLETED,
    DEPLOYMENT_FAILED,
    ROLLBACK_STARTED,
    ROLLBACK_COMPLETED,
    HEALTH_CHECK_PASSED,
    HEALTH_CHECK_FAILED,
    APPROVAL_REQUESTED,
    APPROVAL_GRANTED,
    APPROVAL_DENIED
}
